export enum ConfigKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  MONGO_URI = 'MONGO_URI',
  API_AUTH_ENABLED = 'API_AUTH_ENABLED',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_REDIRECT_URL_SUCCESS = 'GOOGLE_REDIRECT_URL_SUCCESS',
  GOOGLE_REDIRECT_URL_FAILURE = 'GOOGLE_REDIRECT_URL_FAILURE',
  VAPID_PUBLIC_KEY = 'VAPID_PUBLIC_KEY',
  VAPID_PRIVATE_KEY = 'VAPID_PRIVATE_KEY',
  APP_EMAIL = 'APP_EMAIL'
}
